[package]
name = "egui-rust-wgpu-hello"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19.1"
egui = "0.26.0"
raw-window-handle = "0.6.0"
egui-wgpu = { version = "0.26.0",features = ["winit"] }
egui-winit = "0.26.0"
winit = "0.29.4"
pollster = "0.3.0"
